# Generated by Django 2.1.7 on 2019-02-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gitLink',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
