# Generated by Django 2.1.7 on 2019-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_job_gitlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
